# Variables to add in Azure DevOps:
# - ExampleVariable

variables:
  InternalNuGetFeed: ''

trigger: none

stages:
  - stage: Build
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: Build
        steps:
          - checkout: self
            fetchDepth: 0

          - task: gitversion/setup@0
            inputs:
              versionSpec: '5.x'
            displayName: 'Setup GitVersion'

          - task: gitversion/execute@0
            inputs:
              updateAssemblyInfo: true
            displayName: 'Execute GitVersion'

          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                # Set the path to the Directory.Build.props file
                $propsFilePath = "Directory.Build.props"

                # Load the contents of the file
                $propsFile = [xml](Get-Content $propsFilePath)

                # Update the version number if they are not equal
                $propsFile.Project.PropertyGroup.Version = "$(GitVersion.SemVer)"
                $propsFile.Project.PropertyGroup.AssemblyVersion = "$(GitVersion.AssemblySemVer)"
                $propsFile.Save($propsFilePath)
            displayName: 'Update Directory.Build.props version'

          - task: DotNetCoreCLI@2
            inputs:
              command: 'build'
              projects: '**/*.csproj'
              arguments: '--configuration $(BuildConfiguration)'
            displayName: 'Build'
            
          - task: DotNetCoreCLI@2
            inputs:
              command: 'test'
              projects: '**/*[Tt]ests/*.csproj'
              arguments: '--configuration $(BuildConfiguration)'
            displayName: 'Test'
            
          - task: DotNetCoreCLI@2
            inputs:
              command: 'pack'
              packagesToPack: '**/*.csproj'
              versioningScheme: 'byEnvVar'
              versionEnvVar: 'GitVersion.NuGetVersionV2'
            displayName: 'Pack'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: $(Build.ArtifactStagingDirectory)
              artifactName: NugetBuild
            displayName: 'Publish build artifacts'

  - stage: Deploy
    dependsOn: Build
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: DeployToFeed
        steps:
          - checkout: none

          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: NugetBuild

          - task: NuGetCommand@2
            inputs:
              command: 'push'
              packagesToPush: '$(Pipeline.Workspace)/*.nupkg'
              nuGetFeedType: 'internal'
              publishVstsFeed: '$(InternalNuGetFeed)'